# @package _global_
#
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    cpus_per_task: 4
    mem_gb: 64
    gres: h100:2
    timeout_min: 7200
    array_parallelism: 100 # max num of tasks to run in parallel (via job array)
    setup:
      - "eval \"$(micromamba shell hook --shell bash)\""
      - "micromamba activate srt"
