# @package _global_
#
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: unkillable
    cpus_per_task: 6
    mem_gb: 32
    gres: gpu:1
    timeout_min: 2880
    array_parallelism: 100 # max num of tasks to run in parallel (via job array)
    setup:
      - "module purge"
      - "module load miniconda/3"
      - "conda activate srt"
    additional_parameters:
      nodelist: cn-a[001-011],cn-c[001-040],cn-l[001-091]
